name = "SerializedArrays"
uuid = "621c0da3-e96e-4f80-bd06-5ae31cdfcb39"
authors = ["ITensor developers <support@itensor.org> and contributors"]
version = "0.1.1"

[deps]
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
DiskArrays = "3c3547ce-8d99-4f5e-a174-61eb10b00ae3"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[weakdeps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extensions]
SerializedArraysAdaptExt = "Adapt"
SerializedArraysLinearAlgebraExt = "LinearAlgebra"

[compat]
Adapt = "4.3.0"
ConstructionBase = "1.5.8"
DiskArrays = "0.4.12"
LinearAlgebra = "1.10"
Serialization = "1.10"
julia = "1.10"
